### PR TITLE
Added parser for MOOS-IvP NODE_REPORT messages

### PR DESCRIPTION
**Pull request by torsten-pf**
MOOS-IvP (https://oceanai.mit.edu/moos-ivp) uses string messages called NODE_REPORT to publish information about vehicles.
This parser extracts the information needed to display the vehicles on PosiView.

### CODE REVIEW

**Comment by jrenken** [comment]
Merged [ff7a4b9](https://github.com/jrenken/qgis-PosiView/pull/11/commits/ff7a4b99a1ba2ca33a68c173318b18b83111954c) and [9ad2824](https://github.com/jrenken/qgis-PosiView/pull/11/commits/9ad2824327ef7127364b49d7bbcba42136fdd364)

**Comment by jrenken** [comment]
I like the idea to display additional information in the label. But I would prefer a more general approach without any moos_mode dependencies in mobile_item. I would suggest a general 'mode' key. The stripping of the '@' should happen in the parser.

**Comment by jrenken** [comment]
I tried a more general way of displaying text in the label: [extraText](https://github.com/jrenken/qgis-PosiView/tree/extraText)

**Comment by torsten-pf** [comment]
That looks good to me, many thanks! I will try it out.

**Comment by torsten-pf** [comment]
Oh, there is a problem: The mode not always contains the `@` character. We have to replace the lambda in parser_moos_nodereport.py:

```python
'mode': ('text', lambda x: x.split('@')[1] if '@' in x else x)
```

**Comment by jrenken** [comment]
I changed the parser and merged everything into master.
Thanks for your contribution.

**Pull request closed without merging**
